FLGO-108 DB column names
FantLab/FantLab-Go pull request #114
Opened 2019-07-30 17:06 UTC by kenrube

Названия полей/столбцов не менял

2019-07-30 17:26 UTC, geor-kasapidi requested changes

2019-07-30 17:26 UTC, geor-kasapidi commented on app/db/user.go
> +	Code             string    `db:"code;unique;not null"`
`db:"code" gorm:"unique;not null"`

2019-07-30 17:26 UTC, geor-kasapidi commented on app/db/blog.go
> +	TopicLikeId uint32    `db:"topic_like_id;unique;not null"`
`db:"topic_like_id" gorm:"unique;not null"`

2019-07-30 17:26 UTC, geor-kasapidi commented on app/db/genres.go
> -		wg.work_genre_group_id ASC, wg.level ASC`
явное лучше неявного!

2019-07-31 06:37 UTC, kenrube commented on app/db/genres.go
> -		wg.work_genre_group_id ASC, wg.level ASC`
GoLand подсвечивает, мол, `unnecessary`.

2019-07-31 06:59 UTC, geor-kasapidi commented on app/db/genres.go
> -		wg.work_genre_group_id ASC, wg.level ASC`
ничоси он умный)

2019-07-31 07:08 UTC, geor-kasapidi approved these changes

2019-07-31 07:09 UTC, merged