FLGO-109 Forum raw SQL
FantLab/FantLab-Go pull request #121
Opened 2019-08-03 14:51 UTC by kenrube

2019-08-03 20:59 UTC, geor-kasapidi requested changes

2019-08-03 20:59 UTC, geor-kasapidi commented on app/db/forum.go
> +		IFNULL(f.last_message_date, '0000-00-00 00:00:00') AS last_message_date,
тут все норм гарантированно будет с форматом?

2019-08-03 20:59 UTC, geor-kasapidi commented on app/db/forum.go
> +	ORDER BY md.forum_id, u.user_class DESC, u.level DESC`
давай перенесем тоже текст после ORDER BY на другую строчку

2019-08-03 20:59 UTC, geor-kasapidi commented on app/db/forum.go
> +	forumExistsModifiedQuery, forumExistsQueryArgs, err := sqlx.In(forumExistsQuery, forumID, availableForums)
как же остро не хватает дженериков в таких случаях( заглянул в имплементацию `In` метода - рефлексия на рефлексии( ждемс Go 2!!!

2019-08-03 20:59 UTC, geor-kasapidi commented on app/db/forum.go
> +	err = db.X.Get(&shortTopic, db.X.Rebind(shortTopicModifiedQuery), shortTopicQueryArgs...)
есть предложение - сделать все слайсы, которые передаются в качестве параметров в SQL, слайсами строк и потом делать над ними join. Это явно проще операция чем `In`+`Rebind`, но при этом слайс остается слайсом, а не строчкой с запятыми, что дает возможность использовать этот слайс и в других кейсах..

2019-08-05 17:16 UTC, kenrube commented on app/db/forum.go
> +		IFNULL(f.last_message_date, '0000-00-00 00:00:00') AS last_message_date,
Да, так задается нулевая datetime

2019-08-05 17:16 UTC, kenrube commented on app/db/forum.go
> +	ORDER BY md.forum_id, u.user_class DESC, u.level DESC`
Перенес

2019-08-05 17:17 UTC, kenrube commented on app/db/forum.go
> +	err = db.X.Get(&shortTopic, db.X.Rebind(shortTopicModifiedQuery), shortTopicQueryArgs...)
Обсудили, в Sqlx только так (если без хаков и костылей)

2019-08-05 17:18 UTC, kenrube commented on app/db/forum.go
> +	forumExistsModifiedQuery, forumExistsQueryArgs, err := sqlx.In(forumExistsQuery, forumID, availableForums)
Ждем-с

2019-08-06 13:06 UTC, geor-kasapidi approved these changes

2019-08-06 13:06 UTC, merged