FLGO-178 implement signed token based auth
FantLab/FantLab-Go pull request #179
Opened 2020-01-19 19:25 UTC by geor-kasapidi

2020-01-19 19:39 UTC, geor-kasapidi commented
Как работает:

токены в ПРе - это не JWT, но принцип тот же: данные (в этом случае протобаф), подписанные ключиком. В момент логина создается пара токен+рефреш. Токен - это подписанные байтики, рефреш - обычный uuid. Прото модель токена, который подписываем представляет из себя айди токена + дату выпуска + инфу о юзере. В базу записывается айди токена, айди пользователя, хэш рефреш-токена и дата выпуска. Когда токен протухает, нужно с рефрешем и этим токеном сходить в спец ручку auth/refresh, которая выпустит новую пару токенов. По сути рефреш-токен это такой недопароль, который позволяет продлить сессию. В качестве алгоритма подписи используется EdDSA. Данные юзера, которые хранятся в токене, содержат: айди юзера, инфу - забанен ли он и класс развития. Благодаря этому я переписал миддлвары и убрал оттуда запросы в базу. Очень удобно. **Проблема с инвалидацией данных** - пока что я выставил срок жизни токена в 10 минут. Мы говорили про полчаса, но надо переобсудить этот момент, так как в обсуждении не касались факта хранения данных в токене. Возможно имеет смысл засунуть в токен еще что-то пользовательское, например доступные форумы. Срок жизни рефреша - 30 дней как и обсуждали.

2020-01-19 20:01 UTC, geor-kasapidi commented on proto/common.proto
> +        USER_CLASS_UNKNOWN = 0;
убрать _

2020-01-21 10:41 UTC, g0ddest commented on docs/generated.md
> +        class: int32         # класс
Бывает отрицательный class?

2020-01-21 10:41 UTC, g0ddest commented on sources/server/internal/db/forum.go
> +	UserClass   uint8     `db:"user_class"`
А тут class уже uint8, а не int32 🤔

2020-01-21 10:41 UTC, g0ddest commented on sql/auth_tokens.sql
> +CREATE TRIGGER `drop_user_auth_tokens` AFTER UPDATE ON `users` FOR EACH ROW
Может сделать это не триггером, а вызывать вручную, если юзер поставил соответствующую галочку при смене пароля (она может быть выбрана по дефолту)?

2020-01-21 10:41 UTC, g0ddest commented on sql/auth_tokens.sql
> +  `device_info` text NOT NULL,
У mysql есть тип JSON, можно будет потом использовать его для разных запросов аналитических, там можно по нему даже индексы строить.

2020-01-21 10:41 UTC, g0ddest commented on sources/server/internal/config/app.go
> +	RefreshTokenTimeout = 30 * 24 * time.Hour
30 дней не мало для перелогина? По идее это же должен быть долгоживущий токен.

2020-01-21 10:41 UTC, g0ddest commented on sources/server/internal/endpoints/api.go
> +		DeviceInfo:  "", // TODO:
Тут по идее просто из ревеста вытащить строку

2020-01-21 10:41 UTC, g0ddest commented on sources/server/internal/endpoints/refresh_auth.go
> +				Context: "Ожидайте " + dt.String(),
А если очень хочется обновить токен? Скажем, изменилось что-то в константах юзера, которые хранятся в jwt, или jwt потерялся, а остался только рефреш?

2020-01-21 10:41 UTC, g0ddest commented on sources/server/internal/middlewares/check_auth_expiration.go
> +			w.Header().Set("X-Auth-Expired", dt.String())
Получается в любой ответ будет возвращаться такой хидер? А смысл в нем, если данные о времени истечения хранится в jwt. 
При этом, кстати, рефреш токен не хранит в себе дату not_after, что не очень удобно.

2020-01-21 10:41 UTC, geor-kasapidi commented on sql/auth_tokens.sql
> +CREATE TRIGGER `drop_user_auth_tokens` AFTER UPDATE ON `users` FOR EACH ROW
это значит что нужно лезть в перл ;)

2020-01-21 10:43 UTC, geor-kasapidi commented on sql/auth_tokens.sql
> +  `device_info` text NOT NULL,
json не нужен - предполагается что это будет некая строка вида devicename. Чтобы юзер мог однозначно понять что за сессия.

2020-01-21 10:43 UTC, geor-kasapidi commented on sources/server/internal/config/app.go
> +	RefreshTokenTimeout = 30 * 24 * time.Hour
да, и если ты за 30 дней не зашел в приложение - будь добр залогинься ручками

2020-01-21 10:44 UTC, geor-kasapidi commented on sources/server/internal/endpoints/api.go
> +		DeviceInfo:  "", // TODO:
будет отдельный пулл реквест когда мобилки будут готовы к новому апи.

2020-01-21 10:45 UTC, geor-kasapidi commented on sources/server/internal/middlewares/check_auth_expiration.go
> +			w.Header().Set("X-Auth-Expired", dt.String())
issued_at удобнее - так как ты можешь динамически менять срок жизни токена на сервере без перегенерации всех токенов

2020-01-21 10:45 UTC, geor-kasapidi commented on sources/server/internal/middlewares/check_auth_expiration.go
> +			w.Header().Set("X-Auth-Expired", dt.String())
хидер возвращается для дебажных целей - больше смысла в нем нет

2020-01-21 10:46 UTC, geor-kasapidi commented on sources/server/internal/db/forum.go
> +	UserClass   uint8     `db:"user_class"`
потому что это DB модель - размер филда как в таблице

2020-01-21 10:46 UTC, geor-kasapidi commented on docs/generated.md
> +        class: int32         # класс
так генерится потому что протобуфные енумы в Го становятся int32

2020-01-21 10:46 UTC, g0ddest commented on sql/auth_tokens.sql
> +  `device_info` text NOT NULL,
Да, я понимаю, но мы в обсуждении говорили о какой-то стоке, типа json со всеми данными, которые можно собрать и по которым можно идентифицировать девайс. Если потом надо будет как-то это дело сагерировать, или еще какую-то мини-аналитику сделать, то лучше бы, чтобы это поле сразу имело такую возможность.

2020-01-21 10:47 UTC, geor-kasapidi commented on sources/server/internal/endpoints/refresh_auth.go
> +				Context: "Ожидайте " + dt.String(),
ну значит перелогин ручками) вроде несложно

2020-01-21 10:47 UTC, g0ddest commented on sources/server/internal/middlewares/check_auth_expiration.go
> +			w.Header().Set("X-Auth-Expired", dt.String())
Если для дебага только, то ок :-)

2020-01-21 10:48 UTC, geor-kasapidi commented on sources/server/internal/endpoints/api.go
> +		DeviceInfo:  "", // TODO:
я пока не очень определился куда их слать - в хедерах или в боди только этого запроса( яснее станет когда мобилки будем делать

2020-01-21 10:49 UTC, g0ddest commented on sources/server/internal/endpoints/refresh_auth.go
> +				Context: "Ожидайте " + dt.String(),
Ну оно несложно, только я не вижу смысла :-) Рефреш же есть, зачем юзера лишний раз напрягать?

2020-01-21 10:49 UTC, geor-kasapidi commented on sql/auth_tokens.sql
> +  `device_info` text NOT NULL,
окей, переделаю на json)

2020-01-21 10:50 UTC, geor-kasapidi commented on sources/server/internal/endpoints/refresh_auth.go
> +				Context: "Ожидайте " + dt.String(),
ну в принципе можно убрать эту проверку - да, уберу)

2020-01-21 10:55 UTC, kenrube requested changes

2020-01-21 10:55 UTC, kenrube commented on docs/generated.md
> +* **refresh_token** (form, string) - нет описания
Можем добавить описание?

2020-01-21 10:55 UTC, kenrube commented on sources/base/edsign/coder.go
> +		panic(ErrKey)
Этот panic будет перехвачен и обработан где-нибудь? Иначе паниковать на проде кажется не самой лучшей идеей

2020-01-21 10:55 UTC, kenrube commented on sources/server/internal/endpoints/api.go
> +		if len(user.AvailableForumIds) > 0 {
Эта проверка точно нужна? Для залогиненного юзера вроде всегда есть группа, а в группе всегда есть поле со списком форумов

2020-01-21 10:55 UTC, kenrube commented on sources/server/internal/endpoints/api.go
> +		DeviceInfo:  "", // TODO:
В отдельной задаче будет сделано?

2020-01-21 11:49 UTC, geor-kasapidi commented on docs/generated.md
> +* **refresh_token** (form, string) - нет описания
могу написать по русски "рефреш-токен" ;)

2020-01-21 11:49 UTC, geor-kasapidi commented on sources/base/edsign/coder.go
> +		panic(ErrKey)
это паника может произойти только на старте - когда и создается этот обьект. По аналогии с базой, etc.

2020-01-21 11:51 UTC, geor-kasapidi commented on sources/server/internal/endpoints/api.go
> +		if len(user.AvailableForumIds) > 0 {
это дополнительная проверка на случай если у тебя из токена не удастся достать это значение - моделька например неправильно сформировалась или при формировании модельки не удалось распарсить строку из бд

2020-01-21 11:51 UTC, geor-kasapidi commented on sources/server/internal/endpoints/api.go
> +		DeviceInfo:  "", // TODO:
ага - когда мобилки будем прикручивать)

2020-01-21 12:09 UTC, kenrube commented on sources/base/edsign/coder.go
> +		panic(ErrKey)
Гуд

2020-01-21 12:09 UTC, kenrube commented on docs/generated.md
> +* **refresh_token** (form, string) - нет описания
обойдемся

2020-01-21 12:10 UTC, kenrube commented on docs/generated.md
> +* **refresh_token** (form, string) - нет описания
смущает "нет описания". может, вместо этого просто пустую строку писать?

2020-01-21 12:39 UTC, geor-kasapidi commented on docs/generated.md
> +* **refresh_token** (form, string) - нет описания
ща кароч добавлю описание) уговорил

2020-01-21 12:44 UTC, kenrube approved these changes

2020-01-21 12:45 UTC, merged