FLGO-69 New forum message
FantLab/FantLab-Go pull request #192
Opened 2020-02-24 19:10 UTC by kenrube

Сделано добавление нового сообщения в форуме. Запросы отчасти поменяны местами для большей эффективности и логически разбиты на отдельные куски, выполняются все в рамках одной транзакции, в отличие от текущей реализации. В то же время, опущены некоторые детали (в порядке их появления в методе [Forum#AddNewMessage](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2711)):
1. Пропущены многочисленные вкрапления кода, которые никак не влияют на дальнейшую работу: `$force`, `$bonus` etc
2. Полностью пропущен [код работы с аттачами](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2824-L2840)
3. Пропущено [удаление файла](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2008) с текстом превью сообщения для данной темы
4. Пропущено [сохранение](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2634-L2649) текста сообщения в файл. На самом деле непонятно, зачем вообще существуют файлы с текстом сообщений форума
5. Пропущен [аплоад аттачей](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2909-L2924) (дубль 2?)
6. Также пропущено [выставление флага](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L4762-L4770) о наличии аттача у сообщения
7. Опущено [условие](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/Forum.pm#L2948-L2952) про непосылание юзеру нотификации о новом сообщении в форуме, если его нет больше 2 лет на сайте. С одной стороны, это несоответствие текущей логике, с другой - это позволило не реализовывать аналог абсолютно чудовищного метода [MemcachedFunctions#MC_GetUserActivityTime](https://github.com/parserpro/fantlab/blob/b519d8cc4e03790a885d455c648f808daf8069dc/pm/MemcachedFunctions.pm#L328-L371). Да и ничего страшного в том, что сообщение рассылается, нет: пользователю без разницы, а нагрузка на базу совсем небольшая

2020-02-24 21:30 UTC, geor-kasapidi requested changes

2020-02-24 21:30 UTC, geor-kasapidi commented on sources/server/internal/db/forum.go
> +			entries := make([]interface{}, len(topicSubscribers))
есть понимание сколько максимально таких чуваков будет? мы не охренеем оповещать 10к человек?

2020-02-24 21:30 UTC, geor-kasapidi commented on sources/server/internal/helpers/message.go
> +func FormatMessage(message string) string {
мне хочется рыдать глядя на этот файл😭

2020-02-24 21:30 UTC, geor-kasapidi commented on sources/server/internal/helpers/message.go
> +	result = regexp.MustCompile("\\s+$").ReplaceAllLiteralString(result, "")
все регулярки надо единожды компилировать - это достаточно тяжелая операция

2020-02-24 21:30 UTC, geor-kasapidi commented on sources/server/internal/helpers/message.go
> +func FormatMessage(message string) string {
я как будет время обязательно сделаю парсер

2020-02-24 21:30 UTC, geor-kasapidi commented on sources/server/internal/db/forum.go
> +			entries := make([]interface{}, len(topicSubscribers))
по крайней мере метод вставки InsertQuery сожрет кучу памяти :/

2020-02-25 10:22 UTC, kenrube commented on sources/server/internal/db/forum.go
> +			entries := make([]interface{}, len(topicSubscribers))
Судя по прошлогоднему дампу, не больше пары сотен человек

2020-02-25 13:44 UTC, geor-kasapidi approved these changes

2020-02-25 17:04 UTC, merged