FLGO-193 Edit forum message
FantLab/FantLab-Go pull request #212
Opened 2020-03-12 22:45 UTC by kenrube

2020-03-13 08:19 UTC, geor-kasapidi requested changes

2020-03-13 08:19 UTC, geor-kasapidi commented on proto/auth.proto
> +            bool can_edit_own_forum_messages = 5;
я предлагаю завести сразу поле аля таблица разрешенных действий

сделать енум в протобафе в этом же файлике аля Permission

а вместо can_edit_own_forum_messages добавить map<Permission, bool>

2020-03-13 14:32 UTC, kenrube commented on proto/auth.proto
> +            bool can_edit_own_forum_messages = 5;
Идея была хороша, но [ничего не выйдет](https://groups.google.com/forum/#!topic/protobuf/ikeldBe60eI)

2020-03-14 12:00 UTC, geor-kasapidi submitted a review, later dismissed

2020-03-14 12:04 UTC, geor-kasapidi approved these changes

2020-03-14 12:04 UTC, merged