FLGO-182 Messages attachments
FantLab/FantLab-Go pull request #280
Opened 2020-04-13 21:27 UTC by kenrube

2020-04-14 21:03 UTC, kenrube commented
Полностью переписал. Теперь аплоад происходит в 2 этапа: сначала вызывается получение урл-а для загрузки (валиден 10 минут), следом аплоад самого файла

2020-04-15 09:16 UTC, geor-kasapidi requested changes

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/helpers/calc.go
> +func GetBase64(text string) string {
у base64 помимо RawURLEncoding есть еще и другие пресеты - смысла большого в этом методе нет

лучше напрямую заюзать base64.RawURLEncoding.EncodeToString([]byte(text)) в коде

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/get_forum_message_draft_file_upload_url.go
> +	if fileCount == api.config.MaxAttachCountPerMessage {
я бы тут проверял на > - мало ли кто-то еще загрузит чего нить

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/get_forum_message_draft_file_upload_url.go
> +			Context: fmt.Sprintf("К сообщению уже приаттачено %d файлов, это максимум", fileCount),
а тут тогда вместо fileCount - api.config.MaxAttachCountPerMessage

2020-04-15 09:16 UTC, geor-kasapidi commented on sql/20200410_2243.pl
> +unless (table('auth_tokens')) {
а ты типа уже этот sql на проде выполнил?

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/cancel_forum_message_draft.go
> +		_ = api.services.DeleteFile(r.Context(), app.ForumMessageDraftFileGroup, dbMessageDraft.DraftId, file.Name)
вот тут я бы поресерчил - можно ли батчем удалять файлы
в случае если нельзя - глянул бы поможет ли каждое удаление в горутину завернуть + wait group

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/get_forum_message_draft_file_upload_url.go
> +	if fileCount == api.config.MaxAttachCountPerMessage {
может вполне оказаться такая ситуация - что кто-то извне загрузит туда доп файл и условие не отработает

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/get_forum_message_file_upload_url.go
> +	if len(params.FileName) == 0 {
я бы еще добавил валидацию на имя файла - какую-нить разумную регулярку

2020-04-15 09:16 UTC, geor-kasapidi commented on sources/server/internal/endpoints/cancel_forum_message_draft.go
> +		_ = api.services.DeleteFile(r.Context(), app.ForumMessageDraftFileGroup, dbMessageDraft.DraftId, file.Name)
а если вдруг решишься просто в горутину выделить отдельно (без wait group - просто в фон), то надо тогда отвязать контекст запроса - иначе он завершится раньше и отменит удаление

2020-04-15 12:13 UTC, kenrube commented on sources/server/internal/helpers/calc.go
> +func GetBase64(text string) string {
Убрал, уже не нужно

2020-04-15 12:13 UTC, kenrube commented on sources/server/internal/endpoints/get_forum_message_draft_file_upload_url.go
> +	if fileCount == api.config.MaxAttachCountPerMessage {
Согласен, поменял

2020-04-15 12:14 UTC, kenrube commented on sources/server/internal/endpoints/get_forum_message_draft_file_upload_url.go
> +			Context: fmt.Sprintf("К сообщению уже приаттачено %d файлов, это максимум", fileCount),
Заменил

2020-04-15 12:14 UTC, kenrube commented on sources/server/internal/endpoints/cancel_forum_message_draft.go
> +		_ = api.services.DeleteFile(r.Context(), app.ForumMessageDraftFileGroup, dbMessageDraft.DraftId, file.Name)
Есть такой метод, заменил

2020-04-15 12:14 UTC, kenrube commented on sources/server/internal/endpoints/get_forum_message_file_upload_url.go
> +	if len(params.FileName) == 0 {
Готово

2020-04-15 12:19 UTC, kenrube commented on sql/20200410_2243.pl
> +unless (table('auth_tokens')) {
Нет, но должно сработать. В чем суть: в Perl есть скрипт `db_update.pl`, который запускается по каким-то там правилам и последовательно запускает все вложенные скрипты, работающие с базой. Так что каждый скрипт не должен, например, пытаться создать таблицу, если она уже есть. Ну и т.д.
Плюс это все написано с использованием хитрых рутин собственного производства, в которые и въедешь-то не сразу.

2020-04-15 12:27 UTC, geor-kasapidi approved these changes

2020-04-15 12:27 UTC, merged