FLGO-317 Incorrect editions bookcase sorting [Fix]
FantLab/FantLab-Go pull request #320
Opened 2020-06-10 09:23 UTC by kenrube

2020-06-12 17:52 UTC, geor-kasapidi requested changes

2020-06-12 17:52 UTC, geor-kasapidi commented on sources/apiserver/internal/endpoints/show_edition_bookcase.go
> +	linkedAuthorRegex := regexp.MustCompile(`\[autor=([0-9]+)](.+?)\[/autor]`)
предлагаю единожды это компилить сверху в var блоке

2020-06-12 17:52 UTC, geor-kasapidi commented on sources/apiserver/internal/endpoints/show_edition_bookcase.go
> +					authorId, _ := strconv.ParseUint(linkedAuthorRegex.ReplaceAllString(author, "$1"), 10, 0)
не очень понял магию

2020-06-12 17:52 UTC, geor-kasapidi commented on sources/apiserver/internal/endpoints/show_edition_bookcase.go
> +func sortEditionsByAuthor(editions []db.BookcaseEdition, dbService *db.DB, context context.Context) error {
можем вынести этот метод в конвертеры и заодно разбить его на пару по меньше? как раз чтобы db не передавать? а то он очень очень сложный для восприятия

2020-06-13 06:05 UTC, kenrube commented on sources/apiserver/internal/endpoints/show_edition_bookcase.go
> +	linkedAuthorRegex := regexp.MustCompile(`\[autor=([0-9]+)](.+?)\[/autor]`)
Согласен, забываю иногда

2020-06-13 06:05 UTC, kenrube commented on sources/apiserver/internal/endpoints/show_edition_bookcase.go
> +					authorId, _ := strconv.ParseUint(linkedAuthorRegex.ReplaceAllString(author, "$1"), 10, 0)
Поле имеет вид `[autor=417]Эдмонд Гамильтон[/autor]`. Надо вытащить 417 как число, вот и вся магия

2020-06-13 07:26 UTC, geor-kasapidi approved these changes

2020-06-13 07:26 UTC, merged