FLGO-259 Add response
FantLab/FantLab-Go pull request #334
Opened 2020-07-18 17:38 UTC by kenrube

2020-07-19 17:45 UTC, geor-kasapidi requested changes

2020-07-19 17:45 UTC, geor-kasapidi commented on sources/apiserver/internal/endpoints/add_response.go
> +			Context: fmt.Sprintf("Вы уже написали достаточно отзывов (%d) на данное произведение", userResponseCountForWork),
Вы уже написали достаточно отзывов (%d) на данное произведение. Хватит. Остановитесь.

2020-07-19 17:45 UTC, geor-kasapidi commented on sources/core/helpers/message.go
> +	smilesRegex := regexp.MustCompile(fmt.Sprintf(":(%s):", strings.Join(smiles, "|")))
я думаю что имеет смысл убрать параметр smiles и вынести компиляцию регекспа наверх (чтобы один раз это сделать)

2020-07-20 04:35 UTC, kenrube commented on sources/apiserver/internal/endpoints/add_response.go
> +			Context: fmt.Sprintf("Вы уже написали достаточно отзывов (%d) на данное произведение", userResponseCountForWork),
Переформулировал

2020-07-20 04:37 UTC, kenrube commented on sources/core/helpers/message.go
> +	smilesRegex := regexp.MustCompile(fmt.Sprintf(":(%s):", strings.Join(smiles, "|")))
Все не так просто, параметр прокидывается из конфига. Все, что я могу придумать без серьезных извращений - lazy load

2020-07-20 08:43 UTC, geor-kasapidi commented on sources/core/helpers/message.go
> +	smilesRegex := regexp.MustCompile(fmt.Sprintf(":(%s):", strings.Join(smiles, "|")))
предлагаю воткнуть такое в конфиг

```go
type Smiles struct {
	table map[string]struct{}
	re    *regexp.Regexp
}

func (sm *Smiles) IsSmile(s string) bool {
	_, ok := sm.table[s]
	return ok
}

func (sm *Smiles) RemoveFromString(s string) string {
	return sm.re.ReplaceAllLiteralString(s, "")
}

func MakeSmiles(list []string) *Smiles {
	table := make(map[string]struct{}, len(list))
	for _, entry := range list {
		table[entry] = struct{}{}
	}
	smiles := &Smiles{
		table: table,
		re:    regexp.MustCompile(fmt.Sprintf(":(%s):", strings.Join(list, "|"))),
	}
	return smiles
}
```

2020-07-20 12:32 UTC, merged