FLGO-45 Fix json fields
FantLab/FantLab-Go pull request #46
Opened 2019-06-28 23:58 UTC by kenrube

2019-06-29 06:09 UTC, geor-kasapidi requested changes

2019-06-29 06:09 UTC, geor-kasapidi commented on modules/forumapi/datacontroller.go
> +					Description: dbForum.Description,
а мы можем description по другому назвать? :) с type и description есть проблемки в свифте

2019-06-29 06:09 UTC, geor-kasapidi commented on modules/forumapi/datacontroller.go
> +				XXX_Id: dbForum.ForumBlockID,
типа эта айдишка не должна светиться?

2019-06-29 06:09 UTC, geor-kasapidi commented on protobuf/schema/forum_models.proto
> +            poll = 2;
https://developers.google.com/protocol-buffers/docs/style - там раздел про енумы

2019-06-29 08:01 UTC, kenrube commented on modules/forumapi/datacontroller.go
> +					Description: dbForum.Description,
Придумаю

2019-06-29 08:03 UTC, kenrube commented on modules/forumapi/datacontroller.go
> +				XXX_Id: dbForum.ForumBlockID,
Ага. Параметр технический, раньше вырезать его из json-а было очень просто, теперь приходится костыли городить.

2019-06-29 08:04 UTC, kenrube commented on protobuf/schema/forum_models.proto
> +            poll = 2;
Эт все здорово, но как сделать, чтоб в json их строковое представление было в нижнем регистре?

2019-06-29 08:14 UTC, geor-kasapidi commented on protobuf/schema/forum_models.proto
> +            poll = 2;
это настолько принципиально? можно указать в маршалере параметр EnumAsInt например

2019-06-29 08:15 UTC, geor-kasapidi commented on modules/forumapi/datacontroller.go
> +				XXX_Id: dbForum.ForumBlockID,
просто, если он не секретный, то может хрен с ним, пускай будет?)

2019-06-29 08:55 UTC, kenrube commented on modules/forumapi/datacontroller.go
> +				XXX_Id: dbForum.ForumBlockID,
Ок. Однако, надобность в аналоге `json:"-"` может возникнуть и в другом месте, мы просто скрываем проблему

2019-06-29 08:57 UTC, kenrube commented on protobuf/schema/forum_models.proto
> +            poll = 2;
Это плохо, когда инструмент навязывает собственные решения и не дает альтернатив.
https://github.com/golang/protobuf/issues/555 - Open, как обычно

2019-06-29 09:01 UTC, kenrube commented on protobuf/schema/forum_models.proto
> +            poll = 2;
Я специально завел строковые значения, чтоб не городить массу непонятных интов для клиентов :) Возвращаться обратно к тому же - не, спасибо

2019-06-29 09:38 UTC, geor-kasapidi commented on protobuf/schema/forum_models.proto
> +            poll = 2;
> Это плохо, когда инструмент навязывает собственные решения и не дает альтернатив.
> [golang/protobuf#555](https://github.com/golang/protobuf/issues/555) - Open, как обычно

в таком случае поддержку кастомных имен надо добавлять во всех языках которые поддерживают протобуф) в общем такое себе - не вижу большой проблемы в том что кейсы енума будут в апперкейсе) ЗАТО_ИХ_СРАЗУ_ЗАМЕТНО!

2019-06-29 09:42 UTC, geor-kasapidi commented on modules/forumapi/datacontroller.go
> +				XXX_Id: dbForum.ForumBlockID,
протобаф планируется использовать только для отдачи клиентам (пока что - дальше хз что будет) и при необходимости можно создавать внутренние модели для конвертации и уже из них создавать протобуфные - например если будет сложный алгоритм преобразования дбшных моделей, иногда эффективней потратить больше памяти для промежуточных моделек. В таком случае не понадобится модификация генератора протомоделек) Но вообще не думаю что будет что-то настолько сложное что понадобится извращаться. ИМХО :)

2019-07-01 08:23 UTC, geor-kasapidi approved these changes

2019-07-01 08:23 UTC, merged