API форума
FantLab/FantLab-Go pull request #5
Opened 2019-06-09 14:47 UTC by kenrube

- API пока обезличенный (нужно выполнение таски про авторизацию)
- По каталогам не раскидано - dependency management я пока не поборол
- Работает на порту 4242.

2019-06-09 15:25 UTC, geor-kasapidi requested changes
я бы после правок добавил бы в этой ветке сам разбиение на модули - если не возражаешь

2019-06-09 15:25 UTC, geor-kasapidi commented on controller.go
> +	page, err := strconv.ParseUint(ctx.Query("page"), 10, 32)
предлагаю page и limit сделать со значениями по умолчанию - проще код будет

2019-06-09 15:25 UTC, geor-kasapidi commented on controller.go
> +		if gin.IsDebugging() {
вот эту конструкию if else я бы вынес отдельно в какой-нибудь util класс

2019-06-09 15:25 UTC, geor-kasapidi commented on db.go
> +			"u.user_class * 1000000 + u.level AS sort").
такие строки явно нуждаются в комментах)

2019-06-09 15:25 UTC, geor-kasapidi commented on api.go
> +	for _, dbForum := range dbForums {
вот тут я бы что-то пооптимизировал сразу - как минимум dbModerators сделать хэш таблицей явно не помешает.

2019-06-09 15:25 UTC, geor-kasapidi commented on api.go
> +			currentForumBlockId = dbForum.ForumBlockId
непонятно - выглядит так, как будто ждем что входной массив будет отстортирован. Я бы forumBlocks тогда сделал бы хэш таблицей где ключ - айдишка, а значение - массив форумов.

2019-06-09 17:40 UTC, kenrube commented on controller.go
> +	page, err := strconv.ParseUint(ctx.Query("page"), 10, 32)
Limit итак сделан со значением по-умолчанию (на сайте 20), а насчет page я не уверен. Клиенты ведь не будут писать дублирующий код для случая, когда они запрашивают без page (такая ситуация ровно одна, page=1) и с page. Поэтому поле и оставлено обязательным

2019-06-09 17:41 UTC, kenrube commented on controller.go
> +		if gin.IsDebugging() {
Гуд, вынесу, еще не раз пригодится

2019-06-09 17:41 UTC, kenrube commented on db.go
> +			"u.user_class * 1000000 + u.level AS sort").
Знать бы еще как прокомментировать :) Но ок, допишу

2019-06-09 17:42 UTC, kenrube commented on api.go
> +	for _, dbForum := range dbForums {
Хорошая идея, так и сделаю

2019-06-09 17:43 UTC, kenrube commented on api.go
> +			currentForumBlockId = dbForum.ForumBlockId
А вот это не сделаю - входной массив действительно был отсортирован при запросе в базу, поэтому на выходе всегда будет детерминированный порядок.
И да, разумеется, я не против, если ты разобьешь это месиво на модули :)

2019-06-09 18:17 UTC, geor-kasapidi commented on api.go
> +			currentForumBlockId = dbForum.ForumBlockId
тогда напиши что на входе требуется отсортированный массив) мой поинт в том что такие вещи никак компилятором не проверяются

2019-06-09 18:51 UTC, kenrube commented on api.go
> +			currentForumBlockId = dbForum.ForumBlockId
так это ж вроде очевидно из запроса к базе - там прям выдающийся двойной order by :)
```
Order("fb.level, f.level")
```
в противном случае придется в каждом маппинге расписывать предопределенный порядок, а то и заводить в итоговом json-е отдельной место под порядковый номер. я наоборот старался этот момент упростить - все элементы в массиве идут уже в гарантированно строгом итоговом порядке и на клиенте ничего сортировать не требуется

2019-06-09 21:49 UTC, geor-kasapidi commented on api.go
> +			currentForumBlockId = dbForum.ForumBlockId
ок, убедил :)

2019-06-10 12:03 UTC, geor-kasapidi approved these changes

2019-06-10 12:27 UTC, merged